### ISSUE TITLE
Col renmae error

### ISSUE THREAD

**Issue by parikhhm** [USF-HII/tabutil#14]
tabutil col --rename --spec=rename.txt input.txt > output.txt
Traceback (most recent call last):
  File "/home/parikhh/software/tabutil/.venv/bin/tabutil", line 11, in <module>
    load_entry_point('tabutil==0.8.0', 'console_scripts', 'tabutil')()
  File "/home/parikhh/software/tabutil/.venv/lib/python3.5/site-packages/tabutil-0.8.0-py3.5.egg/tabutil/cli.py", line 262, in main
  File "/home/parikhh/software/tabutil/.venv/lib/python3.5/site-packages/tabutil-0.8.0-py3.5.egg/tabutil/cli.py", line 62, in subcommand_col
  File "/home/parikhh/software/tabutil/.venv/lib/python3.5/site-packages/tabutil-0.8.0-py3.5.egg/tabutil/cli.py", line 62, in <listcomp>
IndexError: list index out of range

**Comment by countdigi** [comment]
Is it possible to change the spec-file delimiter from `:` character to `\t' character.
