### ISSUE TITLE
Fix bug w/ data type for row extract

### ISSUE THREAD

**Issue by countdigi** [USF-HII/tabutil#4]
```
(.venv) ✔ ~/dev/usf-hii/fac-parikhh-rdn-smt [master|✔]
countskm@deckard$ tabutil row --extract=Teddy1:apple example-data/tabutil.tsv 
/home/countskm/dev/usf-hii/fac-parikhh-rdn-smt/.venv/lib/python2.7/site-packages/pandas/core/ops.py:792: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = getattr(x, name)(y)
Traceback (most recent call last):
  File "/home/countskm/dev/usf-hii/fac-parikhh-rdn-smt/.venv/bin/tabutil", line 11, in <module>
    load_entry_point('tabutil==0.6.0', 'console_scripts', 'tabutil')()
  File "/home/countskm/dev/usf-hii/fac-parikhh-rdn-smt/.venv/lib/python2.7/site-packages/tabutil/cli.py", line 100, in main
    args.func(args)
  File "/home/countskm/dev/usf-hii/fac-parikhh-rdn-smt/.venv/lib/python2.7/site-packages/tabutil/cli.py", line 45, in subcommand_row
    print(tabutil.core.extract_rows(df, column_value_pair[0][0], column_value_pair[0][1]))
  File "/home/countskm/dev/usf-hii/fac-parikhh-rdn-smt/.venv/lib/python2.7/site-packages/tabutil/core.py", line 5, in extract_rows
    return(df.loc[df[column_name] == value].to_csv(sep='\t'))
  File "/home/countskm/dev/usf-hii/fac-parikhh-rdn-smt/.venv/lib/python2.7/site-packages/pandas/core/ops.py", line 855, in wrapper
    res = na_op(values, other)
  File "/home/countskm/dev/usf-hii/fac-parikhh-rdn-smt/.venv/lib/python2.7/site-packages/pandas/core/ops.py", line 794, in na_op
    raise TypeError("invalid type comparison")
TypeError: invalid type comparison
```

**Comment by countdigi** [comment]
The initial dataframe is now set to convert all information into the string type to eliminate this issue.
